import java.util.Date;


public class ObjectHasher extends Hasher{

	/**
	Hashing a given object without using Object's built-in
	hashcode function.
	@param obj The object to be hashed
	@return int value generated by hashing the object 
*/
	public int hash(Object obj) {
		//Gets the Objects value as a string
		String string = obj.toString();
		//The hashcode to be generated
		int hashcode = 0;
		
		//Gets the value for each char in a string and multiplies it by the next prime number
		for (int x = 0; x < string.length(); x++) {
			hashcode += string.charAt(x) * generatePrime(x);
		}
		
		return hashcode;
	}

	/**
	Simple function to identify the coder.
	@return String that is your name.
	 */
	public String getCoderName() {
		
		return "Jack Proudfoot";
	}
	
	/**
	 * A method to generate the next greatest prime number
	 * 
	 * @return int Returns the next greatest prime number
	 * @param int Number to start search
	 */
	private static int generatePrime (int num) {
		
		for(int x = 2; x * 2 < num; x++) {
	        if(num % x == 0) {
				return generatePrime(++num);
			}
		}
		
		return num;
	}
	
}
